### ISSUE TITLE
Code errored out when check the server 

### ISSUE THREAD

**Issue by Aerospace911** [vertecx/nagios-plugins#3]
i have used this command before and the ip 0.0.0.0 works fine but i recently change my distribution of linux but now when i run the command python3 check_minecraft.py -H 0.0.0.0 -p 37733
I get this

0:00:00.000024: Iteration 1/5: Connecting to 0.0.00 on port 37733.
0:00:00.000340: Iteration 1/5: Sending Server List Ping.
Traceback (most recent call last):
  File "/home/aerospace/check_minecraft.py", line 150, in <module>
    main()
  File "/home/aerospace/check_minecraft.py", line 112, in main
    info = get_server_info(args.hostname, args.port, args.num_checks, args.timeout, args.verbose)
  File "/home/aerospace/check_minecraft.py", line 47, in get_server_info
    s.send(MC_SERVER_LIST_PING)
TypeError: a bytes-like object is required, not 'str'

**Comment by Aerospace911** [comment]
my bad i forgot to upgrade it to python3

**Comment by Aerospace911** [comment]
https://superuser.com/questions/1346368/see-if-minecraft-server-is-online-with-linux-terminal
